### ISSUE TITLE
What to do with Darwin_core.xls

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/inva-occurrences#4]
@mcoupremanne what is the file [Darwin_core.xls](https://github.com/mcoupremanne/Exotic-plants-occurrences-in-Wallonia/blob/master/Darwin_core.xls)?

- It seems to be a Darwin Core mapping of the source data, and thus not source data itself
- It seems to be cut of at 65.536 rows (a limitation of excel)
- It is quite big to put under version control

I would therefore argue not to put this file in this repository. @mcoupremanne, I assume you have a SQL or other script to map the source data to Darwin Core, so a Darwin Core view can always be recreated by you?

**Comment by mcoupremanne** [comment]
Yes @peterdesmet  , it was added to have an overview of the content but it indeed exceeds the Excel Limit. I remove it.
The entire work is based on a SQL. So the file can be re-generated at any time.

**Comment by peterdesmet** [comment]
Nice! 👍
