### ISSUE TITLE
What to do with Exotic_flora_in_Wallonia_metada_Reviewed.docx

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/inva-occurrences#5]
Hi @mcoupremanne, I assume [Exotic_flora_in_Wallonia_metada_Reviewed](https://github.com/mcoupremanne/Exotic-plants-occurrences-in-Wallonia/blob/master/Exotic_flora_in_Wallonia_metada_Reviewed.docx) is the file where you wrote the metadata for this dataset?

Would it be OK to move this to a Google Document and give us access? That will make it easier to suggest changes and work together.

**Comment by mcoupremanne** [comment]
@peterdesmet  It is the metada document, that have been reviewed by  DEMNA involved officers (No google drive based co-working) . 
For our exchanges, you are right it will be easier to go with google doc : 
https://drive.google.com/open?id=13lP9kj790Y2FbQdKr9byamvGH74m2cI0

**Comment by peterdesmet** [comment]
Great! I made it into a Google doc that I shared with you. Not sure when we'll be able to review though. :-)
