### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by mcoupremanne** [trias-project/inva-occurrences#6]
Issues #1  to #3  have been solved in the 1.5 Version. I took the liberty to close the issues.

**Comment by peterdesmet** [comment]
Thanks @mcoupremanne!

It's easier for us if you reply to the specific issues that it has been resolved in version 1.5, but leave the issue open. That gives us a chance to review and close/discuss further.

**Comment by peterdesmet** [comment]
Just reviewed v1.5 and indicated in #1 and #3. All good, closing this issue.

**Comment by mcoupremanne** [comment]
Thanks @peterdesmet  I'll let the issues open for the next times!
++
Max
