### ISSUE TITLE
Delay publication 

### ISSUE THREAD

**Issue by mcoupremanne** [trias-project/inva-occurrences#8]
Still waiting for a last very formal check from colleagues, for a while now. This is the only thing that prevents the publication (trying to hurry colleagues - all is already in our IPT, only need the green light to press the publication button).

So I leave the respective files here so you can have a view @LienReyserhove , @damianooldoni  , @peterdesmet  . By this time, I'm working on  our DBs for the first update with increased publishable content. Very sorry for bad predictions of the delays. (End of June still ok to have first update published).

PS. dataset ID will be the one attributed by GBIF.
Best regards

**Comment by peterdesmet** [comment]
Thanks for the update @mcoupremanne! Where can we find the "respective files" (I assume data)?

**Comment by mcoupremanne** [comment]
The data files are : 
* 'trias-project/inva-occurrences/Faune_exotique_OccurrenceCore.csv' for the 'fusion' (focus on exotic animals occurrences only within all databases we have).
* 'trias-project/inva-occurrences/MI_OccurrenceCore.zip for the hydrobiology unit'dataset that can be fully published (not only exotic taxa).

I hope there was no problem importing these in github, if I did something wrong let me know and I'll correct ASAP.
Best regards @peterdesmet ,
Maxime.

**Comment by peterdesmet** [comment]
Ok, a couple of questions/remarks

- CSV files under 10.000 records are ok to upload on GitHub, but know that these are public
- Zip files are not ideal for GitHub. If it is a smaller csv, you can upload them as such, otherwise share them via WeTransfer or other with us for checking
- Please upload Darwin Core files to a `data/processed` directory
- If I understand correctly, there are two datasets: exotic occurrences across databases + a full hydriobiology unit dataset. Will these be published as two datasets? I would suggest to do so!

**Comment by peterdesmet** [comment]
Also [Faune_exotique_OccurrenceCore.csv](https://github.com/trias-project/inva-occurrences/blob/master/Faune_exotique_OccurrenceCore.csv) only contains headers. 😄

**Comment by peterdesmet** [comment]
Let us know if you encounter any issues (e.g. creating directories).

**Comment by mcoupremanne** [comment]
> Also [Faune_exotique_OccurrenceCore.csv](https://github.com/trias-project/inva-occurrences/blob/master/Faune_exotique_OccurrenceCore.csv) only contains headers.

Sorry, I Do this kind of things all day long, first guy bored about this is myself haha.

**Comment by mcoupremanne** [comment]
> Ok, a couple of questions/remarks
> 
> * CSV files under 10.000 records are ok to upload on GitHub, but know that these are public

** I thik it is ok about the files beeing public, actualy everything should already be on GBIF, but it is a last very very formal check on metadata that makes it that slow.**

> * Zip files are not ideal for GitHub. If it is a smaller csv, you can upload them as such, otherwise share them via WeTransfer or other with us for checking

** Ok, thanks for the tip I had no idea. I'll use WeTransfer so, because one file is > 130 K records (and the other is about 6 K records normally, not only headers ^^).**

> * Please upload Darwin Core files to a `data/processed` directory

**OK**

> * If I understand correctly, there are two datasets: exotic occurrences across databases + a full hydriobiology unit dataset. Will these be published as two datasets? I would suggest to do so!

Yes, maybe I was not that clear, but exotic occurrences accross databases is not a good way of publishing for long term .In the future, it should be replaced by all original datasets (sources compiled) having each one his own dedicated GBIF publication but it implies a lot (looooot) of work for each one, that do not only rely on me. The aim of the 'fusion' publication was to focus on the urgent content in a first time.

**Comment by peterdesmet** [comment]
Completely agree on publishing original datasets (long term). But what will the current situation be: 2 datasets (fusion and hydro)?

**Comment by mcoupremanne** [comment]
Yes, exactly : one fusionc (exluding hydrobio data of course) and one hydrobio dataset. Is that OK for you?

**Comment by peterdesmet** [comment]
Yes, 2 datasets makes perfect sense. If you send the data files @LienReyserhove can have a quick look.

**Comment by peterdesmet** [comment]
Datasets are now published: https://www.gbif.org/dataset/search?publishing_org=a6f344b0-1944-4354-8376-272495c9135e
